services:
  ika_sim:
    build: .
    container_name: ika_container
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    stdin_open: true
    tty: true
